[build]
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "10.15.3"


[dev]
  command = "yarn run dev"


[[redirects]]
  from = "/images/tiny/*"
  to = "https://lazy-load-nlm.netlify.com/images/:splat/?nf_resize=fit&w=20"
  status = 200

[[redirects]]
  from = "/images/small/*"
  to = "https://lazy-load-nlm.netlify.com/images/:splat/?nf_resize=fit&w=500"
  status = 200

[[redirects]]
  from = "/images/medium/*"
  to = "https://lazy-load-nlm.netlify.com/images/:splat/?nf_resize=fit&w=600"
  status = 200

[[redirects]]
  from = "/images/large/*"
  to = "https://lazy-load-nlm.netlify.com/images/:splat/?nf_resize=fit&w=700"
  status = 200

[[redirects]]
  from = "/images/original/*"
  to = "https://lazy-load-nlm.netlify.com/images/:splat/"
  status = 200
